CREATE CONSTRAINT repository_identity IF NOT EXISTS FOR (n:Repository) REQUIRE n.repository_id IS UNIQUE;
CREATE CONSTRAINT snapshot_identity IF NOT EXISTS FOR (n:Snapshot) REQUIRE n.key IS UNIQUE;
CREATE CONSTRAINT ac_identity IF NOT EXISTS FOR (n:AC) REQUIRE n.key IS UNIQUE;
CREATE CONSTRAINT adr_identity IF NOT EXISTS FOR (n:ADR) REQUIRE n.key IS UNIQUE;
CREATE CONSTRAINT component_identity IF NOT EXISTS FOR (n:Component) REQUIRE n.key IS UNIQUE;
CREATE CONSTRAINT source_file_identity IF NOT EXISTS FOR (n:SourceFile) REQUIRE n.key IS UNIQUE;
CREATE CONSTRAINT test_identity IF NOT EXISTS FOR (n:Test) REQUIRE n.key IS UNIQUE;
CREATE CONSTRAINT decision_identity IF NOT EXISTS FOR (n:Decision) REQUIRE n.key IS UNIQUE;
CREATE CONSTRAINT lesson_identity IF NOT EXISTS FOR (n:Lesson) REQUIRE n.key IS UNIQUE;
CREATE INDEX ac_scope IF NOT EXISTS FOR (n:AC) ON (n.generation_key, n.canonical_id);
CREATE INDEX adr_scope IF NOT EXISTS FOR (n:ADR) ON (n.generation_key, n.canonical_id);
CREATE INDEX component_scope IF NOT EXISTS FOR (n:Component) ON (n.generation_key, n.canonical_id);
CREATE INDEX source_file_scope IF NOT EXISTS FOR (n:SourceFile) ON (n.generation_key, n.canonical_id);
CREATE INDEX test_scope IF NOT EXISTS FOR (n:Test) ON (n.generation_key, n.canonical_id);
CREATE INDEX decision_scope IF NOT EXISTS FOR (n:Decision) ON (n.generation_key, n.canonical_id);
CREATE INDEX lesson_scope IF NOT EXISTS FOR (n:Lesson) ON (n.generation_key, n.canonical_id);
CREATE INDEX ac_name IF NOT EXISTS FOR (n:AC) ON (n.name);
CREATE INDEX adr_name IF NOT EXISTS FOR (n:ADR) ON (n.name);
CREATE INDEX component_name IF NOT EXISTS FOR (n:Component) ON (n.name);
CREATE INDEX source_file_name IF NOT EXISTS FOR (n:SourceFile) ON (n.name);
CREATE INDEX test_name IF NOT EXISTS FOR (n:Test) ON (n.name);
