"""
MODULE: install_pre_commit_shims
GOAL: Idempotently install pre-commit hook shims for every stage declared in
    .pre-commit-config.yaml, so that every worktree and fresh clone has all
    required hooks active without a manual ``pre-commit install`` invocation.
BUSINESS CONTEXT: The async SQL test pipeline (PR #39) was silently disabled
    because ``pre-commit install --hook-type post-commit`` refused to run when
    ``core.hooksPath`` had any value (even the default). This module writes
    shims directly — bypassing pre-commit's overly-conservative guard — using
    the existing pre-commit shim as a template or a bundled fallback. Prevents
    silent hook omissions in future worktree and clone setups.
ARCHITECTURE: Pure stdlib + PyYAML (transitive via pre-commit). Four public
    functions: ``find_hooks_dir`` (locates the hooks directory respecting
    core.hooksPath), ``collect_stages`` (parses declared stages from YAML),
    ``_shim_template`` (produces shim content from template or bundled
    fallback), ``install_shims`` (orchestrates idempotent installation).
    Directly runnable: ``python scripts/commit_guardian/install_pre_commit_shims.py``.
    Non-destructive: never overwrites foreign (non-pre-commit-generated) hooks.
"""

from __future__ import annotations

import configparser
import subprocess
import sys
import traceback
from pathlib import Path

import yaml


# ---------------------------------------------------------------------------
# Bundled fallback shim template
# ---------------------------------------------------------------------------

_FALLBACK_SHIM_TEMPLATE = """\
#!/bin/sh
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type={stage})
HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")
if command -v pre-commit > /dev/null; then
    exec pre-commit "${{ARGS[@]}}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
"""

_PRE_COMMIT_SIGNATURE = "# File generated by pre-commit"
_TEMPLATE_HOOK_TYPE_BYTES = b"--hook-type=pre-commit"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def find_hooks_dir(repo_root: Path) -> Path:
    """Return the resolved hooks directory for the repository.

    Parses ``<repo_root>/.git/config`` for a ``[core] hooksPath`` entry.
    When the key is set, the value is resolved relative to *repo_root*.
    When absent, defaults to ``<repo_root>/.git/hooks``.

    Args:
        repo_root: Absolute path to the main repository root (the directory
            that contains ``.git/``).

    Returns:
        Resolved absolute Path to the hooks directory.
    """
    git_config_path = repo_root / ".git" / "config"
    if git_config_path.is_file():
        parser = configparser.RawConfigParser(strict=False)
        parser.read(git_config_path, encoding="utf-8")
        hooks_path_value = parser.get("core", "hooksPath", fallback=None)
        if hooks_path_value:
            candidate = Path(hooks_path_value)
            if not candidate.is_absolute():
                candidate = repo_root / candidate
            return candidate.resolve()
    return (repo_root / ".git" / "hooks").resolve()


def collect_stages(repo_root: Path) -> list[str]:
    """Return a sorted, deduplicated list of stages declared in ``.pre-commit-config.yaml``.

    Walks every ``repos[*].hooks[*].stages`` list in the YAML file and
    collects explicit stage values.  Hooks that omit ``stages:`` are NOT
    counted — only stages that are explicitly declared in the YAML are
    returned (per the pre-commit spec: the default stage is ``pre-commit``
    but that shim is assumed to exist from onboarding).

    Args:
        repo_root: Absolute path to the repository root that contains
            ``.pre-commit-config.yaml``.

    Returns:
        Sorted list of distinct stage name strings found in the YAML.

    Raises:
        FileNotFoundError: If ``.pre-commit-config.yaml`` does not exist.
        yaml.YAMLError: If the file cannot be parsed as YAML.
    """
    config_path = repo_root / ".pre-commit-config.yaml"
    with config_path.open(encoding="utf-8") as fh:
        config = yaml.safe_load(fh)

    stages: set[str] = set()
    for repo_entry in config.get("repos", []):
        for hook in repo_entry.get("hooks", []):
            for stage in hook.get("stages", []):
                stages.add(stage)

    return sorted(stages)


def _shim_template(hooks_dir: Path, stage: str) -> str:
    """Return the shim content for *stage* derived from the pre-commit template.

    If ``<hooks_dir>/pre-commit`` exists and carries the pre-commit signature,
    it is read as bytes; ``--hook-type=pre-commit`` is substituted with
    ``--hook-type=<stage>`` and the result is returned as a string.

    If the pre-commit shim is absent or is not pre-commit-generated, the
    bundled fallback template is used instead.

    Args:
        hooks_dir: Path to the hooks directory (output of ``find_hooks_dir``).
        stage: The hook stage name (e.g. ``"post-commit"``).

    Returns:
        String content for the new shim file with LF line endings.
    """
    pre_commit_path = hooks_dir / "pre-commit"
    if pre_commit_path.is_file():
        raw = pre_commit_path.read_bytes()
        if _PRE_COMMIT_SIGNATURE.encode() in raw:
            target_bytes = f"--hook-type={stage}".encode()
            substituted = raw.replace(_TEMPLATE_HOOK_TYPE_BYTES, target_bytes)
            return substituted.decode(errors="replace")

    # Bundled fallback: use {{ }} escapes so .format() only touches {stage}
    return _FALLBACK_SHIM_TEMPLATE.format(stage=stage)


def install_shims(repo_root: Path) -> dict[str, str]:
    """Idempotently install pre-commit shims for all declared stages.

    Reads the declared stages from ``.pre-commit-config.yaml``, then for each
    stage (excluding ``pre-commit`` — assumed to already exist from onboarding):

    - If the target shim file already exists and carries the pre-commit
      signature → skip with result ``"already_installed"``.
    - If the target shim file exists but lacks the signature → skip and
      warn with result ``"skipped_foreign"``.
    - Otherwise → write the shim and set the executable bit, result
      ``"installed"``.

    A one-line summary is printed to stdout for each stage processed.

    Args:
        repo_root: Absolute path to the repository root.

    Returns:
        Dictionary mapping stage name to result string
        (``"installed"``, ``"already_installed"``, or ``"skipped_foreign"``).
    """
    hooks_dir = find_hooks_dir(repo_root)
    hooks_dir.mkdir(parents=True, exist_ok=True)

    stages = collect_stages(repo_root)
    results: dict[str, str] = {}

    for stage in stages:
        if stage == "pre-commit":
            continue

        shim_path = hooks_dir / stage
        result = _evaluate_existing_shim(shim_path, stage)
        if result is not None:
            results[stage] = result
            print(f"[{result}] {stage}")
            continue

        content = _shim_template(hooks_dir, stage)
        shim_path.write_bytes(content.encode().replace(b"\r\n", b"\n"))
        _set_executable(shim_path)
        results[stage] = "installed"
        print(f"[installed] {stage}")

    return results


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _evaluate_existing_shim(shim_path: Path, stage: str) -> str | None:
    """Return the result string if *shim_path* already exists, else None.

    Args:
        shim_path: Path to the shim file that may or may not exist.
        stage: Stage name, used only for the warning message.

    Returns:
        ``"already_installed"`` if the existing file carries the pre-commit
        signature, ``"skipped_foreign"`` if it exists but does not carry the
        signature, or ``None`` if the file does not exist.
    """
    if not shim_path.exists():
        return None

    header = shim_path.read_bytes()[:200]
    if _PRE_COMMIT_SIGNATURE.encode() in header:
        return "already_installed"

    print(
        f"WARNING: Skipping {stage}: existing hook is not a "
        "pre-commit-generated shim",
        file=sys.stderr,
    )
    return "skipped_foreign"


def _set_executable(path: Path) -> None:
    """Set the executable bit on *path* (no-op on Windows).

    Args:
        path: Path to the file whose permissions should be updated.
    """
    try:
        path.chmod(path.stat().st_mode | 0o111)
    except (NotImplementedError, OSError):
        pass  # Windows: chmod is a no-op; Git for Windows uses the shebang


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        )
        repo_root = Path(result.stdout.strip())
        install_shims(repo_root)
        sys.exit(0)
    except Exception:
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)

# ====================================================================
# DECISION HISTORY
# ====================================================================
# - 2026-05-13 09:00 [Agent/ticket-supervisor]: Initial implementation (#EPIC-LeafcutterMVP/01)
#   (TICKET-20260513-AutoInstall_PreCommit_Hook_Shims). Created to fix
#   the silent async-SQL-pipeline failure caused by pre-commit refusing
#   to install post-commit shim when core.hooksPath was set. Writes
#   shims directly from the existing pre-commit shim as a template (or
#   bundled fallback), bypassing pre-commit's overly-conservative guard.
#   Idempotent: skips already-installed shims; preserves foreign hooks.
#   Directly runnable: python scripts/commit_guardian/install_pre_commit_shims.py
# - 2026-05-13 12:00 [epic-supervisor/ticket-13]: Changed ConfigParser() (#EPIC-LeafcutterMVP/01)
#   to RawConfigParser(strict=False) in find_hooks_dir to tolerate
#   duplicate option keys in .git/config (e.g. [core] on multi-worktree
#   setups). ConfigParser strict=True raises DuplicateOptionError;
#   RawConfigParser with strict=False reads the last value silently.
# ====================================================================
