"""
MODULE: unit_tests/commit_guardian/_ge_127b_1_fixture.py
COVERS: GE-127b-1 -- "A change that leaves an already-oversized file longer
    than it was is refused; one that leaves it the same or shorter is
    allowed" (shared fixture module -- carries no tests of its own)

GOAL: Fixture builders shared by test_ge_127b_1_grown_and_shrunk.py,
    test_ge_127b_1_boundary_and_new_file.py,
    test_ge_127b_1_history_and_seam.py, and
    test_ge_127b_1_reachability_and_deployed.py -- extracted verbatim from
    the single test_ge_127b_1.py module (GE-127f-2, "PROPORTION AND
    SPLITTING, BECAUSE THIS GATE JUDGES ITS OWN TESTS": that record's own
    added-line comparison would otherwise refuse this very split's host
    file, since it stood at 414 counted lines against its own 400-line
    ratcheted previous length before this split). Every one of GE-127b-1's
    original 8 test methods, its docstrings, its `# covers:` / `# angle:`
    tags, and every assertion move to the sibling test modules UNCHANGED;
    only the shared scaffolding below is factored out to a single place, per
    this repo's established `_ge_127a_1_ordinary_commit_fixture.py` /
    `_ge_127c_1_scope_fixture.py` / `_ge_127e_*_fixture.py` precedent.

EXERCISE STRATEGY (per CLAUDE.md "Gate / Workflow ACs -- Verify
    Behaviorally, Not by Grep" and this repo's Fixture Authenticity Rule):
    every behavioural descriptor built from these helpers performs a REAL
    `git init`, REAL commits establishing HEAD state, and a REAL `git add`
    staging a change, then invokes the REAL check_file_size.py (or, for the
    reachability descriptor, the REAL run_hook.py wrapper; for the deployed
    descriptor, the REAL scripts/build.py output) as a subprocess and reads
    the actual process exit code and stdout/stderr -- never a source-grep,
    never a direct function call against an in-memory fixture describing a
    "previous size". The exit code IS the commit outcome: 0 = commit
    completes, non-zero = commit is refused.

    All fixture file content is generated by this module's own content()
    helper rather than a checked-in literal, EXCEPT the "deployed" descriptor,
    which uses the REAL, on-disk content of scripts/build.py mutated by a
    single in-place, non-quote-touching edit that leaves both the raw and the
    docstring-stripped line count identical -- the survivability proof the
    keystone record exists to make true. (Originally scripts/build_phases.py,
    cited by the AC as "largest: scripts/build_phases.py at 2603 counted /
    3873 raw" -- that file was subsequently split by the build_phases.py
    size-limit refactor and is now 340 counted lines, UNDER the 400-line
    limit, so it no longer exercises this test's premise. scripts/build.py is
    ~1915 counted lines and remains genuinely, tracked-ly oversized;
    repointed here.)

DECISION HISTORY
- 2026-09-01 [GE-127b-1/test-writer]: Initial authoring of all eight RED
    test stubs per GE-127b-1's test_spec, in a single test_ge_127b_1.py
    module. Verified RED via `python -m unittest discover -s
    unit_tests/commit_guardian -t . -p "test_ge_127b_1.py"` -- see the
    test-writer sign-off comment on that ticket for the exact captured
    failures.
- 2026-09-28 [GE-127f-2/test-writer, round 1]: NARROWED
    test_ge_127b_1_an_oversized_file_left_at_exactly_its_previous_length_commits
    to
    test_ge_127b_1_an_oversized_file_edited_only_in_unmeasured_content_commits_at_its_previous_length,
    per GE-127f-2's own reconciliation notes and architect-review ruling.
    The narrowed edit was net-zero (414 -> 414 counted lines) but
    gross-non-zero (9 measured lines inserted), which the ticket flagged as
    self-refusing once GE-127f-2's own gate landed.
- 2026-09-28 [GE-127f-2/test-writer, round 2]: SPLIT test_ge_127b_1.py into
    this shared fixture module plus four focused test modules, resolving the
    self-refusal flagged in round 1 by shrinking each resulting file well
    under the 400-line limit rather than by any exemption -- this epic's own
    standing precedent (tickets 02-06 each split their own oversized new
    test files the same way). No test, assertion, or tag was altered from
    round 1; only the module boundaries moved.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
COMMIT_GUARDIAN_DIR = REPO_ROOT / "templates" / "scripts" / "commit_guardian"
CHECK_FILE_SIZE = COMMIT_GUARDIAN_DIR / "check_file_size.py"
RUN_HOOK = COMMIT_GUARDIAN_DIR / "run_hook.py"
BUILD_PY = REPO_ROOT / "scripts" / "build.py"
CONFIG_PATH = COMMIT_GUARDIAN_DIR / "commit_guardian.json"
# scripts/build.py -- genuinely oversized post the build_phases.py size-
# limit split (see module docstring EXERCISE STRATEGY for why it replaces
# scripts/build_phases.py, now under-limit at 340 counted lines).
REAL_OVERSIZED_FILE = REPO_ROOT / "scripts" / "build.py"

PYTHON = sys.executable
SUBPROCESS_TIMEOUT_SECONDS = 30
BUILD_TIMEOUT_SECONDS = 120

# Read the REAL per-extension limit from the real config, rather than
# hardcoding a number that could silently drift out of sync with it.
CONFIG = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
PY_LIMIT = CONFIG["file_size"]["line_limits"][".py"]


# ---------------------------------------------------------------------------
# Git plumbing -- a real repo, real commits, real staging.
# ---------------------------------------------------------------------------


def git(args: list[str], cwd: Path, check: bool = True) -> subprocess.CompletedProcess:
    """Run a real git command in *cwd*.

    Args:
        args: Arguments to pass to `git` (without the leading "git").
        cwd: Working directory to run the command in.
        check: Whether to raise on non-zero exit (fixture setup only).

    Returns:
        The completed process.
    """
    return subprocess.run(
        ["git", *args],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=SUBPROCESS_TIMEOUT_SECONDS,
        check=check,
    )


def init_repo(root: Path) -> None:
    """Initialize a real git repository with a deterministic committer identity."""
    git(["init", "-q"], root)
    git(["config", "user.email", "test-writer@example.com"], root)
    git(["config", "user.name", "GE-127b-1 test fixture"], root)


def commit_all(root: Path, message: str) -> None:
    """Stage everything and make a real commit."""
    git(["add", "-A"], root)
    git(["commit", "-q", "-m", message], root)


def stage_all(root: Path) -> None:
    """Stage everything without committing."""
    git(["add", "-A"], root)


def content(n_lines: int, tag: str = "v", docstring: str | None = None) -> str:
    """Build deterministic, docstring-free plain-text file content, or --
    when *docstring* is given -- the same content preceded by a triple
    -quoted docstring holding it (entirely stripped by count_content_lines,
    so it contributes zero measured lines; see GE-127f-2's narrowed boundary
    descriptor, the only caller that passes it).

    No triple-quote or block-comment delimiter appears anywhere in the
    body, so check_file_size.py's docstring/comment stripping only ever
    touches the optional leading docstring, and the counted length is
    always exactly `n_lines`.

    Args:
        n_lines: Exact number of lines the resulting content must count as.
        tag: A label folded into each line, used to make two same-length
            fixtures textually distinguishable.
        docstring: When given, wraps the body in a leading triple-quoted
            docstring holding this text.

    Returns:
        Content ending in a single trailing newline, counting as n_lines
        measured lines regardless of *docstring*.
    """
    return (f'"""\n{docstring}\n"""\n' if docstring else "") + "\n".join(f"{tag}_{i:06d} = {i}" for i in range(n_lines)) + "\n"


def run_check(cwd: Path) -> subprocess.CompletedProcess:
    """Invoke the real check_file_size.py against staged content in *cwd*."""
    return subprocess.run(
        [PYTHON, str(CHECK_FILE_SIZE)],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=SUBPROCESS_TIMEOUT_SECONDS,
    )


def run_check_via_hook(cwd: Path) -> subprocess.CompletedProcess:
    """Invoke check_file_size.py through the registered run_hook.py wrapper."""
    return subprocess.run(
        [PYTHON, str(RUN_HOOK), str(CHECK_FILE_SIZE)],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=SUBPROCESS_TIMEOUT_SECONDS,
    )


def first_editable_line_index(lines: list[str]) -> int:
    """Find a line with no triple-quote/comment-block delimiter to mutate.

    Editing a line that contains no triple-double-quote, triple-single-quote,
    or C-style block-comment delimiter in place (never adding or removing a
    line) leaves both the raw line count and
    the docstring/comment-stripped line count of the surrounding file
    completely unchanged -- a genuine size-neutral edit.

    Args:
        lines: The file's lines (from str.splitlines()).

    Returns:
        Index of a safe, non-empty line to mutate.

    Raises:
        AssertionError: If no such line exists (fixture sanity failure).
    """
    for i, line in enumerate(lines):
        if line.strip() and '"""' not in line and "'''" not in line and "/*" not in line and "*/" not in line:
            return i
    raise AssertionError("no safe line found to apply a size-neutral edit to")


class RatchetFixtureTestCase(unittest.TestCase):
    """Shared tempdir + git-repo scaffolding."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name)
        init_repo(self.root)


class DeployedFixtureTestCase(unittest.TestCase):
    """Shared tempdir scaffolding for the deployed (build.py output) descriptor."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.target = Path(self._tmp.name)


if __name__ == "__main__":
    raise SystemExit("this module holds shared fixtures only -- run the sibling test_ge_127b_1_*.py modules instead")
