"""
MODULE: unit_tests/commit_guardian/test_ge_127b_1.py
COVERS: GE-127b-1 -- "A change that leaves an already-oversized file longer
    than it was is refused; one that leaves it the same or shorter is
    allowed"

GOAL: RED test-first stubs for the ratchet behaviour. The production module
    under test, templates/scripts/commit_guardian/check_file_size.py, exists
    today but has NO notion of a file's previous length at all -- it only
    ever compares the file's current (staged) length against a fixed
    per-extension limit, unconditionally, for every staged file regardless
    of direction of change. python-coder must add the previous-length
    ratchet described in GE-127b-1's it_requirements (read via
    `git show HEAD:<path>`, one shared measurement function called twice) to
    make these tests green.

BUSINESS CONTEXT: see
    docs/acceptance-criteria/guardrail-engine/GE-127-files-stay-workable/GE-127b-1.yaml
    and its parent GE-127b.yaml. This is the KEYSTONE record of the GE-127
    goal: it is what makes the size gate switchable without a wall of false
    alarms, because ~200 tracked .py files already exceed their limit.

EXERCISE STRATEGY (per CLAUDE.md "Gate / Workflow ACs -- Verify
    Behaviorally, Not by Grep" and this repo's Fixture Authenticity Rule):
    every behavioural descriptor below performs a REAL `git init`, REAL
    commits establishing HEAD state, and a REAL `git add` staging a change,
    then invokes the REAL check_file_size.py (or, for the reachability
    descriptor, the REAL run_hook.py wrapper; for the deployed descriptor,
    the REAL scripts/build.py output) as a subprocess and reads the actual
    process exit code and stdout/stderr -- never a source-grep, never a
    direct function call against an in-memory fixture describing a
    "previous size". The exit code IS the commit outcome: 0 = commit
    completes, non-zero = commit is refused. This mirrors the established
    pattern in unit_tests/commit_guardian/test_ge_122a_1.py and
    unit_tests/commit_guardian/test_bp_1100g_3_i.py in this same directory.

    All fixture file content is generated by this module's own
    _content() helper rather than a checked-in literal, EXCEPT the
    "deployed" descriptor, which uses the REAL, on-disk content of
    scripts/build_phases.py (the AC's own cited evidence: "largest:
    scripts/build_phases.py at 2603 counted / 3873 raw") mutated by a
    single in-place, non-quote-touching edit that leaves both the raw and
    the docstring-stripped line count identical -- the survivability proof
    the keystone record exists to make true.

NAMED MUTATIONS (BA's injections, carried per the AC's mandate that they be
    executed and not merely described): the two "commit is allowed" tests
    (shrink-still-over, and new-file-below-limit) are the ones a
    permit-everything OR a freeze-everything implementation both pass
    trivially; the ANTI-STALE-BASELINE test and the SEAM test below are the
    two descriptors that a naive implementation is most likely to get wrong
    even once a ratchet of some kind exists. Mutation execution against a
    real implementation (confirming each goes RED when the corresponding bad
    behaviour is reintroduced) is the pr-reviewer's / python-coder's
    responsibility once production code exists; today (greenfield) every
    descriptor is RED because the previous-length notion does not exist at
    all.

DECISION HISTORY
- 2026-09-01 [GE-127b-1/test-writer]: Initial authoring of all eight RED
    test stubs per GE-127b-1's test_spec. Verified RED via
    `python -m unittest discover -s unit_tests/commit_guardian -t . -p
    "test_ge_127b_1.py"` -- see the test-writer sign-off comment on the
    ticket for the exact captured failures.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
_COMMIT_GUARDIAN_DIR = _REPO_ROOT / "templates" / "scripts" / "commit_guardian"
_CHECK_FILE_SIZE = _COMMIT_GUARDIAN_DIR / "check_file_size.py"
_RUN_HOOK = _COMMIT_GUARDIAN_DIR / "run_hook.py"
_BUILD_PY = _REPO_ROOT / "scripts" / "build.py"
_CONFIG_PATH = _COMMIT_GUARDIAN_DIR / "commit_guardian.json"
_REAL_OVERSIZED_FILE = _REPO_ROOT / "scripts" / "build_phases.py"

_PYTHON = sys.executable
_SUBPROCESS_TIMEOUT_SECONDS = 30
_BUILD_TIMEOUT_SECONDS = 120

# Read the REAL per-extension limit from the real config, rather than
# hardcoding a number that could silently drift out of sync with it.
_CONFIG = json.loads(_CONFIG_PATH.read_text(encoding="utf-8"))
_PY_LIMIT = _CONFIG["file_size"]["line_limits"][".py"]


# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------


def _git(args: list[str], cwd: Path, check: bool = True) -> subprocess.CompletedProcess:
    """Run a real git command in *cwd*.

    Args:
        args: Arguments to pass to `git` (without the leading "git").
        cwd: Working directory to run the command in.
        check: Whether to raise on non-zero exit (fixture setup only).

    Returns:
        The completed process.
    """
    return subprocess.run(
        ["git", *args],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=_SUBPROCESS_TIMEOUT_SECONDS,
        check=check,
    )


def _init_repo(root: Path) -> None:
    """Initialize a real git repository with a deterministic committer identity."""
    _git(["init", "-q"], root)
    _git(["config", "user.email", "test-writer@example.com"], root)
    _git(["config", "user.name", "GE-127b-1 test fixture"], root)


def _commit_all(root: Path, message: str) -> None:
    """Stage everything and make a real commit."""
    _git(["add", "-A"], root)
    _git(["commit", "-q", "-m", message], root)


def _stage_all(root: Path) -> None:
    """Stage everything without committing."""
    _git(["add", "-A"], root)


def _content(n_lines: int, tag: str = "v") -> str:
    """Build deterministic, docstring-free plain-text file content.

    No triple-quote or block-comment delimiters appear anywhere in the
    output, so check_file_size.py's docstring/comment stripping is a no-op
    and the counted length is exactly `n_lines`.

    Args:
        n_lines: Exact number of lines the resulting content must count as.
        tag: A label folded into each line, used to make two same-length
            fixtures textually distinguishable.

    Returns:
        Content ending in a single trailing newline, counting as n_lines.
    """
    return "\n".join(f"{tag}_{i:06d} = {i}" for i in range(n_lines)) + "\n"


def _run_check(cwd: Path) -> subprocess.CompletedProcess:
    """Invoke the real check_file_size.py against staged content in *cwd*."""
    return subprocess.run(
        [_PYTHON, str(_CHECK_FILE_SIZE)],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=_SUBPROCESS_TIMEOUT_SECONDS,
    )


def _run_check_via_hook(cwd: Path) -> subprocess.CompletedProcess:
    """Invoke check_file_size.py through the registered run_hook.py wrapper."""
    return subprocess.run(
        [_PYTHON, str(_RUN_HOOK), str(_CHECK_FILE_SIZE)],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=_SUBPROCESS_TIMEOUT_SECONDS,
    )


class RatchetFixtureTestCase(unittest.TestCase):
    """Shared tempdir + git-repo scaffolding."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name)
        _init_repo(self.root)


# ---------------------------------------------------------------------------
# 1. The mandatory negative arm
# ---------------------------------------------------------------------------


class TestOversizedFileGrownByOneLineIsRefused(RatchetFixtureTestCase):
    def test_ge_127b_1_an_oversized_file_made_one_line_longer_is_refused_naming_both_lengths(self):
        # covers: GE-127b-1
        # covers: GE-127b
        # angle: criterion
        """THE MANDATORY NEGATIVE ARM. An already-oversized covered file
        (410 lines, permitted length 400) committed to HEAD, then staged one
        line longer (411 lines), must be refused, and the outcome must state
        BOTH the length the file stood at before (410) and the length it
        stands at after (411).

        RED TODAY: check_file_size.py already refuses this file (it refuses
        any file over the absolute limit unconditionally), but it never
        prints the PREVIOUS length anywhere in its output -- only the
        current line count and the limit. The assertion on the previous
        length is what fails.
        """
        before = _PY_LIMIT + 10
        after = before + 1
        big = self.root / "big.py"
        big.write_text(_content(before), encoding="utf-8")
        _commit_all(self.root, "establish oversized file")

        big.write_text(_content(after), encoding="utf-8")
        _stage_all(self.root)

        result = _run_check(self.root)

        self.assertNotEqual(
            0,
            result.returncode,
            msg=(
                "A commit that grows an already-oversized file by one line "
                f"must be refused. stdout={result.stdout!r} stderr={result.stderr!r}"
            ),
        )
        combined = result.stdout + result.stderr
        self.assertIn(
            str(before),
            combined,
            msg=f"Outcome must state the PREVIOUS length ({before}). Got: {combined!r}",
        )
        self.assertIn(
            str(after),
            combined,
            msg=f"Outcome must state the length AFTER the change ({after}). Got: {combined!r}",
        )


# ---------------------------------------------------------------------------
# 2. Shrink arm -- the mechanism, not a concession (NAMED MUTATION target)
# ---------------------------------------------------------------------------


class TestOversizedFileShrunkCommitsCleanly(RatchetFixtureTestCase):
    def test_ge_127b_1_an_oversized_file_made_shorter_commits_and_is_not_refused_for_still_being_over(self):
        # covers: GE-127b-1
        # covers: GE-127b
        # angle: criterion
        """A change leaving an already-oversized covered file SHORTER than
        it stood before, while still above its permitted length, must
        commit cleanly.

        NAMED MUTATION (BA injection 1): an implementation that judges the
        file against its FIXED permitted length instead of its own previous
        length refuses this commit (the freeze the parent L1 names as the
        failure mode). This descriptor must be RED under that mutation and
        green once the ratchet compares against the file's own HEAD length.

        RED TODAY: check_file_size.py refuses ANY file over the absolute
        limit unconditionally -- it has no ratchet at all, so this shrink
        (409 > 400) is refused exactly like the mutation would refuse it.
        """
        before = _PY_LIMIT + 10
        after = before - 1
        self.assertGreater(after, _PY_LIMIT, "fixture sanity: must remain oversized after the shrink")
        big = self.root / "big.py"
        big.write_text(_content(before), encoding="utf-8")
        _commit_all(self.root, "establish oversized file")

        big.write_text(_content(after), encoding="utf-8")
        _stage_all(self.root)

        result = _run_check(self.root)

        self.assertEqual(
            0,
            result.returncode,
            msg=(
                "A change that SHRINKS an already-oversized file (but leaves it "
                f"still over its limit) must commit cleanly. stdout={result.stdout!r} "
                f"stderr={result.stderr!r}"
            ),
        )


# ---------------------------------------------------------------------------
# 3. Boundary: exactly the same length
# ---------------------------------------------------------------------------


class TestOversizedFileUnchangedLengthCommits(RatchetFixtureTestCase):
    def test_ge_127b_1_an_oversized_file_left_at_exactly_its_previous_length_commits(self):
        # covers: GE-127b-1
        # angle: boundary
        """A change leaving an already-oversized covered file at EXACTLY the
        length it stood at before must commit cleanly. The boundary between
        the refuse arm and the allow arm is strictly greater-than, not
        greater-than-or-equal.

        RED TODAY: check_file_size.py refuses this file unconditionally
        because it is over the absolute limit, regardless of whether its
        length changed at all.
        """
        length = _PY_LIMIT + 10
        big = self.root / "big.py"
        big.write_text(_content(length, tag="v"), encoding="utf-8")
        _commit_all(self.root, "establish oversized file")

        # Same LINE COUNT, different content -- a genuine pure edit.
        big.write_text(_content(length, tag="w"), encoding="utf-8")
        _stage_all(self.root)

        result = _run_check(self.root)

        self.assertEqual(
            0,
            result.returncode,
            msg=(
                "A pure edit that leaves an oversized file's length unchanged "
                f"must commit cleanly. stdout={result.stdout!r} stderr={result.stderr!r}"
            ),
        )


# ---------------------------------------------------------------------------
# 4. New file has no previous length -- never coerced to zero (NAMED MUTATION)
# ---------------------------------------------------------------------------


class TestNewFileBelowLimitCommits(RatchetFixtureTestCase):
    def test_ge_127b_1_a_newly_added_file_below_its_limit_commits_and_is_not_treated_as_having_grown(self):
        # covers: GE-127b-1
        # angle: criterion
        """A covered file that did NOT exist before, added at a length
        comfortably below its permitted length, must commit cleanly.

        NAMED MUTATION (BA injection 2): an implementation that treats an
        absent previous length as a previous length of ZERO refuses every
        newly added non-empty covered file (since any positive length
        "grew" from zero). This descriptor must be RED under that mutation.

        This is trivially green on TODAY's implementation (a brand-new
        under-limit file is not refused by the absolute-limit check
        either) -- flagged here as the "satisfied by a guard that refuses
        nothing" case the AC explicitly names; it earns its keep once a
        ratchet exists and must be re-verified with the zero-coercion
        mutation injected at that point.
        """
        (self.root / "README.md").write_text("placeholder\n", encoding="utf-8")
        _commit_all(self.root, "establish baseline with no covered files")

        new_file = self.root / "fresh.py"
        new_file.write_text(_content(50), encoding="utf-8")
        _stage_all(self.root)

        result = _run_check(self.root)

        self.assertEqual(
            0,
            result.returncode,
            msg=(
                "A brand-new covered file below its limit must commit cleanly. "
                f"stdout={result.stdout!r} stderr={result.stderr!r}"
            ),
        )


# ---------------------------------------------------------------------------
# 5. Anti-stale-baseline: the previous length moves with real commit history
# ---------------------------------------------------------------------------


class TestPreviousLengthReadFromHistoryMovesWithIt(RatchetFixtureTestCase):
    def test_ge_127b_1_the_previous_length_is_read_from_the_repository_history_and_moves_with_it(self):
        # covers: GE-127b-1
        # angle: real_artifact
        """THE ANTI-STALE-BASELINE DESCRIPTOR. Establish an oversized
        covered file (500 lines), commit a change that SHRINKS it (450
        lines, still over the 400 limit), then stage a change that grows it
        back by ONE line relative to the NEW shorter length (451 lines) --
        still below the ORIGINAL 500. The commit MUST be refused: a
        recorded baseline that was not updated by the intervening commit
        would see 451 < 500 and wrongly allow it; a `git show HEAD:<path>`
        read sees 451 > 450 (the true, current previous length) and refuses
        it.

        RED TODAY: check_file_size.py refuses this unconditionally anyway
        (it is over the absolute limit), so the assertion on the exit code
        alone is trivially satisfied by today's non-ratcheted
        implementation -- but that means this descriptor cannot yet
        distinguish a correct HEAD-read ratchet from "refuses everything
        over the limit"; the SHRINK commit in test 2 above is the one that
        actually forces the ratchet to exist. This descriptor's role is to
        additionally forbid a STALE recorded baseline once the ratchet
        exists, over real, successive git history.
        """
        original = 500
        shrunk = 450
        grown = shrunk + 1
        self.assertGreater(original, _PY_LIMIT)
        self.assertGreater(shrunk, _PY_LIMIT)
        self.assertLess(grown, original)

        big = self.root / "big.py"
        big.write_text(_content(original), encoding="utf-8")
        _commit_all(self.root, "establish oversized file at original size")

        big.write_text(_content(shrunk), encoding="utf-8")
        _commit_all(self.root, "shrink the oversized file")

        big.write_text(_content(grown), encoding="utf-8")
        _stage_all(self.root)

        result = _run_check(self.root)

        self.assertNotEqual(
            0,
            result.returncode,
            msg=(
                "Growing the file relative to its MOST RECENT committed length "
                "(450 -> 451) must be refused even though 451 is still below the "
                f"file's original size (500). stdout={result.stdout!r} "
                f"stderr={result.stderr!r}"
            ),
        )


# ---------------------------------------------------------------------------
# 6. Seam with GE-127a-1's silence arm
# ---------------------------------------------------------------------------


class TestUnderLimitFileGrowingStaysUnderProducesNoFinding(RatchetFixtureTestCase):
    def test_ge_127b_1_a_file_under_its_limit_that_grows_but_stays_under_produces_no_finding(self):
        # covers: GE-127b-1
        # angle: seam
        """A covered file BELOW its permitted length that the change leaves
        larger but STILL below it must commit cleanly and must not be
        reported as a refused finding. This is the seam with GE-127a-1's
        silence arm: an over-eager ratchet applied to every file (not only
        those already above their limit) refuses ordinary growth
        everywhere.

        RED TODAY only insofar as a correct ratchet must not regress this;
        today's implementation already permits ordinary under-limit growth,
        so this descriptor mainly guards against an over-eager ratchet
        being introduced. It is included so GE-127a-1/GE-127b-1 boundary
        drift is caught the moment it is introduced, not discovered later.
        """
        before = _PY_LIMIT - 50
        after = _PY_LIMIT - 10
        small = self.root / "small.py"
        small.write_text(_content(before), encoding="utf-8")
        _commit_all(self.root, "establish under-limit file")

        small.write_text(_content(after), encoding="utf-8")
        _stage_all(self.root)

        result = _run_check(self.root)

        self.assertEqual(
            0,
            result.returncode,
            msg=(
                "A file that grows but stays under its limit must commit "
                f"cleanly. stdout={result.stdout!r} stderr={result.stderr!r}"
            ),
        )
        refusal_marker = re.search(r"(?i)(too large|refused|❌)", result.stdout)
        if refusal_marker:
            self.assertNotIn(
                "small.py",
                result.stdout[max(0, refusal_marker.start() - 200) : refusal_marker.end() + 200],
                msg="An under-limit file that merely grew must not appear near a refusal marker.",
            )


# ---------------------------------------------------------------------------
# 7. Reachability -- the registered hook entry point
# ---------------------------------------------------------------------------


class TestRatchetVerdictReachesRegisteredHookEntryPoint(RatchetFixtureTestCase):
    def test_ge_127b_1_the_ratchet_verdict_is_emitted_through_the_registered_hook_entry_point(self):
        # covers: GE-127b-1
        # angle: reachability
        """PRODUCTION ENTRY POINT. Run the gate as a subprocess through the
        registered hook path (`run_hook.py check_file_size.py`) with a
        grown oversized file staged, and assert the before-and-after
        lengths appear in the hook's own output stream and that the exit
        status is the commit outcome (non-zero refusal) rather than an
        advisory note. A comparison computed by a function nothing at
        commit time calls is inert.

        RED TODAY: same reason as test 1 -- the previous length is never
        printed anywhere.
        """
        before = _PY_LIMIT + 25
        after = before + 1
        big = self.root / "big.py"
        big.write_text(_content(before), encoding="utf-8")
        _commit_all(self.root, "establish oversized file")

        big.write_text(_content(after), encoding="utf-8")
        _stage_all(self.root)

        result = _run_check_via_hook(self.root)

        self.assertNotEqual(
            0,
            result.returncode,
            msg=(
                "The registered hook entry point must refuse a commit that grows "
                f"an already-oversized file. stdout={result.stdout!r} "
                f"stderr={result.stderr!r}"
            ),
        )
        combined = result.stdout + result.stderr
        self.assertIn(str(before), combined)
        self.assertIn(str(after), combined)


# ---------------------------------------------------------------------------
# 8. Deployed -- the survivability proof over a real oversized tracked file
# ---------------------------------------------------------------------------


def _first_editable_line_index(lines: list[str]) -> int:
    """Find a line with no triple-quote/comment-block delimiter to mutate.

    Editing a line that contains no triple-double-quote, triple-single-quote,
    or C-style block-comment delimiter in place (never adding or removing a
    line) leaves both the raw line count and
    the docstring/comment-stripped line count of the surrounding file
    completely unchanged -- a genuine size-neutral edit.

    Args:
        lines: The file's lines (from str.splitlines()).

    Returns:
        Index of a safe, non-empty line to mutate.

    Raises:
        AssertionError: If no such line exists (fixture sanity failure).
    """
    for i, line in enumerate(lines):
        if line.strip() and '"""' not in line and "'''" not in line and "/*" not in line and "*/" not in line:
            return i
    raise AssertionError("no safe line found to apply a size-neutral edit to")


class TestDeployedCopyRunsRatchetOverRealOversizedFile(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.target = Path(self._tmp.name)

    def test_ge_127b_1_the_deployed_copy_runs_the_ratchet_over_the_repositorys_real_oversized_files(self):
        # covers: GE-127b-1
        # angle: deployed
        """After build.py, the DEPLOYED copy and every module it imports
        must load and run in a cold process -- a helper outside
        templates/scripts/commit_guardian/ with no scripts/build_phases.py
        deploy-map entry surfaces here as ModuleNotFoundError rather than
        passing. Then the survivability proof this record exists for: stage
        a size-neutral edit to one of the repository's genuinely oversized
        tracked files (scripts/build_phases.py, per the AC's own cited
        evidence) and assert the deployed run permits it.

        RED TODAY: check_file_size.py refuses ANY file over the absolute
        limit unconditionally, including a pure size-neutral edit to an
        already-oversized file -- there is no ratchet to permit it yet.
        """
        self.assertTrue(
            _REAL_OVERSIZED_FILE.exists(),
            msg=f"Fixture sanity: {_REAL_OVERSIZED_FILE} must exist in this worktree.",
        )
        real_content = _REAL_OVERSIZED_FILE.read_text(encoding="utf-8")

        build_result = subprocess.run(
            [_PYTHON, str(_BUILD_PY), "--target-dir", str(self.target)],
            capture_output=True,
            text=True,
            timeout=_BUILD_TIMEOUT_SECONDS,
        )
        self.assertEqual(
            0,
            build_result.returncode,
            msg=f"build.py itself failed: stdout={build_result.stdout} stderr={build_result.stderr}",
        )

        deployed_check = self.target / "scripts" / "commit_guardian" / "check_file_size.py"
        self.assertTrue(
            deployed_check.exists(),
            msg=f"{deployed_check} was not deployed by build.py.",
        )

        _init_repo(self.target)
        big = self.target / "big_real.py"
        big.write_text(real_content, encoding="utf-8")
        _commit_all(self.target, "establish real oversized file")

        lines = real_content.splitlines()
        idx = _first_editable_line_index(lines)
        mutated_lines = list(lines)
        mutated_lines[idx] = mutated_lines[idx] + "  # ge-127b-1 size-neutral edit"
        mutated_content = "\n".join(mutated_lines) + ("\n" if real_content.endswith("\n") else "")
        self.assertNotEqual(real_content, mutated_content, "fixture sanity: edit must actually change content")
        big.write_text(mutated_content, encoding="utf-8")
        _stage_all(self.target)

        run_result = subprocess.run(
            [_PYTHON, str(deployed_check)],
            cwd=str(self.target),
            capture_output=True,
            text=True,
            timeout=_SUBPROCESS_TIMEOUT_SECONDS,
        )
        self.assertNotIn(
            "ModuleNotFoundError",
            run_result.stderr,
            msg=(
                "Deployed check_file_size.py crashed importing a dependency from "
                f"the deployed layout. stderr:\n{run_result.stderr}"
            ),
        )
        self.assertEqual(
            0,
            run_result.returncode,
            msg=(
                "A size-neutral edit to a real, already-oversized tracked file "
                "must be permitted by the deployed gate -- a run that refuses it "
                "means the gate cannot be switched on. "
                f"stdout={run_result.stdout!r} stderr={run_result.stderr!r}"
            ),
        )


if __name__ == "__main__":
    unittest.main()
