"""
MODULE: unit_tests/ac_store/_declared_files_fixtures.py
GOAL: Shared fixture construction and real-CLI/real-subprocess invocation helpers
    for the ACD-1600c-4 declared-files test family (test_acd_1600c_4*.py in
    both unit_tests/ac_store/ and unit_tests/commit_guardian/).
BUSINESS CONTEXT: ACD-1600c-4 introduces a new optional AC field
    `declared_files` and a single read seam, scripts/ac_store/declared_files.py,
    that is not yet implemented (this module supports the TDD red baseline for
    that seam and its four child ACs -i/-ii/-iii/-iv). Extracted to a shared
    module so no sibling test file re-implements real-repo-tree and real-CLI
    plumbing, mirroring the precedent of unit_tests/ac_store/_acs_100i_fixtures.py
    and unit_tests/ac_store/_bo_2900a_1_fixtures.py.
ARCHITECTURE: Fixtures are produced by the REAL serializer (yaml.safe_dump) and
    written to real files, never hand-indented literals (Fixture Authenticity
    Rule, test-writer skill S2h.2). The commit-time hook under test is the
    CANONICAL SOURCE at templates/scripts/commit_guardian/check_ac_schema.py —
    NOT the root scripts/commit_guardian/ copy, which is a build output
    (a git-mode-120000 symlink into .leafcutter/, itself regenerated by
    build.py; see .gitignore and ADR-001/ADR-004). Editing or testing-against
    the deployed copy instead of templates/ is exactly the KI-ACS-002 /
    ACD-1600c-4-iii mistake this very AC family exists to catch, so this
    fixture module deliberately points at templates/ and documents why.

SEAM CONTRACT (scripts/ac_store/declared_files.py — NOT YET IMPLEMENTED).
    This is the interface test-writer is specifying for python-coder, derived
    from ACD-1600c-4's it_requirements and criteria text. python-coder's
    implementation must satisfy this shape for the tests below to go green:

      NoDeclaredFiles          — sentinel class; str(instance) == "no declared files"
      NO_DECLARED_FILES        — the one singleton instance of NoDeclaredFiles
      NOT_EVALUATED_LABEL      — str constant "not evaluated: no declared files"
                                  (the exact phrase ACD-1600c-4-ii's it_requirements
                                  say a consuming check must use verbatim)

      get_declared_files(record: dict) -> list[dict] | NoDeclaredFiles
          `declared_files` key absent  -> NO_DECLARED_FILES.
          Otherwise                    -> the declared entries, VERBATIM, in
                                           declared order: [{"path": str,
                                           "state": "existing"|"to_be_created"}, ...].
          Never an empty list; never derived from doc_links.

      declared_files_shape_errors(record_id: str, declared_files_value) -> list[str]
          Structural/semantic errors on the RAW declared_files value, independent
          of the filesystem: empty list -> one message naming record_id saying a
          requirement with no files to declare leaves the list out rather than
          declaring it empty; any entry missing 'path' or carrying an unknown
          'state' -> one message per offending entry naming record_id.

      path_form_errors(record_id: str, declared_files_value, *,
                        build_definition: dict[str, str] | None = None) -> list[str]
          One message per offending entry, purely lexical (no existence check,
          no symlink resolution): absolute path or one that escapes the repo
          root -> "... must be relative to the repository root and stay inside
          it"; a backslash present -> "... forward slashes"; a path under a
          regenerated root (per build_definition, defaulting to
          load_build_definition()'s real mapping when not supplied) -> refused,
          naming the mapped source path, or stating no source could be
          determined when the root maps to no known source.

          H-1 FIX CONTRACT (ACD-1600c-4-iii review finding, red as of this
          test-writer pass): the regenerated-root comparison MUST normalise
          the declared path before matching a `build_definition` prefix —
          resolving a leading './', collapsing repeated slashes, and
          comparing case-insensitively (Windows/macOS filesystems are
          case-insensitive) — so `./.claude/agents/foo.md` and
          `.Claude/agents/foo.md` are BOTH still caught and refused with the
          same "declare '<mapped source>' instead" message the exact-spelling
          case already produces, echoing the path exactly as declared (never
          the normalised form) per the AC's "naming R and the path as
          written" criterion. Separately, ANY declared path whose OWN
          spelling is non-canonical — a leading './', an internal repeated
          '//', or a trailing '/' — that is not itself a regenerated-copy
          match is refused too (never silently accepted, never silently
          normalised through), with a message naming the canonical spelling
          the author must declare instead, quoted on its own
          (`'<canonical>'`), distinct from the quoted original. This is the
          REFUSE (not normalise-and-accept) resolution of that open question:
          the AC is silent on non-canonical spellings, so refusing keeps the
          store's own declared_files values byte-stable and forces the
          author to write the one canonical spelling every time.

      load_build_definition(repo_root: Path | None = None) -> dict[str, str]
          Real mapping of {regenerated_root_prefix: source_root_prefix} read
          from this project's OWN build deploy definition (never a second,
          hard-coded list) — e.g. {".claude/agents/": "templates/agents/"}.

      existence_messages(record: dict, repo_root: Path) -> tuple[list[str], list[str]]
          (refusals, reports) for the existence-vs-marker rule: an 'existing'
          entry absent from repo_root's tree is a refusal UNLESS the record's
          work_status == 'done' (then neither refused nor reported — the iv
          exemption); a 'to_be_created' entry already present is a
          (non-blocking) report UNLESS work_status == 'done'.

      store_wide_report(store_root: Path, repo_root: Path) -> str
          Deterministic text: a "no declared files" section (sorted by id,
          with a total), a "declared existing, now absent (work finished)"
          section (sorted by record id then declared order, with a total),
          and a records-scanned count. Byte-identical across repeated calls.

      main(argv: list[str] | None = None) -> int
          CLI entry point exposing store_wide_report(); exits 0 always (the
          report is informational and never blocks).
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

# unit_tests/ac_store/_declared_files_fixtures.py -> repo root is two parents up.
REPO_ROOT = Path(__file__).resolve().parent.parent.parent

SCHEMA_FILE = REPO_ROOT / "config" / "ac_store_schema.json"

# Self-hosting boundary (ADR-001/ADR-004): scripts/commit_guardian/ at the repo
# root is a git-mode-120000 SYMLINK into .leafcutter/ (a build.py output,
# .gitignore'd) — templates/scripts/commit_guardian/ is the canonical, edited
# source. Testing against the deployed copy instead of templates/ is the
# KI-ACS-002 / BP-1100g-1 mistake ACD-1600c-4-iii exists to catch; this fixture
# module targets templates/ deliberately, matching the established convention
# in unit_tests/commit_guardian/test_check_ac_schema.py.
COMMIT_GUARDIAN_DIR = REPO_ROOT / "templates" / "scripts" / "commit_guardian"
CHECK_AC_SCHEMA_HOOK = COMMIT_GUARDIAN_DIR / "check_ac_schema.py"

# scripts/ac_store/ IS canonical source directly at the repo root (tracked in
# git, no templates/ counterpart, confirmed via `git check-ignore`) — unlike
# commit_guardian, AC-store tooling operates on this repo's own AC store and
# is never deployed into a consumer project's scripts/ tree.
AC_STORE_SCRIPTS_DIR = REPO_ROOT / "scripts" / "ac_store"
VALIDATE_AC_SCHEMA_CLI = AC_STORE_SCRIPTS_DIR / "validate_ac_schema.py"
DECLARED_FILES_MODULE = AC_STORE_SCRIPTS_DIR / "declared_files.py"

_AC_STORE_REL = "docs/acceptance-criteria"


@dataclass
class CliRun:
    """Captured result of a real subprocess invocation."""

    returncode: int
    stdout: str
    stderr: str

    @property
    def combined(self) -> str:
        return self.stdout + self.stderr


def import_declared_files_module():
    """Import scripts/ac_store/declared_files.py as a live module object.

    Raises ModuleNotFoundError today (the module does not exist yet) — that
    IS the correct RED reason for every test whose behavioural assertions
    live below this call and therefore never execute. Each test's assertions
    are written in full regardless, so once python-coder lands a naive or
    partially-wrong module, this import succeeds and the real assertions
    resume discriminating.
    """
    scripts_dir = str(AC_STORE_SCRIPTS_DIR)
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
    import declared_files  # type: ignore[import-not-found]

    return declared_files


def default_ac_fields(ac_id: str, **overrides: Any) -> dict[str, Any]:
    """Return a minimal, valid, DRAFT AC record dict (before yaml.safe_dump).

    Deliberately `readiness: draft` (not `approved`) and criteria text with no
    durable-effect verbs, so the AC's own test-contract
    (`validate_test_contract`) and side-effect-declaration
    (`validate_declares_side_effect`) gates never fire for these fixture
    records — this test family exercises `declared_files` in isolation, not
    those adjacent gates.
    """
    data: dict[str, Any] = {
        "id": ac_id,
        "title": f"Declared-files fixture record {ac_id}",
        "created_by": "unit_tests/ac_store/_declared_files_fixtures.py",
        "component": "ac-driven-dev",
        "components": ["ac_driven_dev", "ac_store"],
        "level": "L3",
        "status": "active",
        "req_status": "draft",
        "work_status": "todo",
        "readiness": "draft",
        "priority": "medium",
        "depends_on": [],
        "doc_links": [],
        "amended_by": [],
        "covered_by": [],
        "implemented_by": [],
        "superseded_by": None,
        "criteria": (
            "Given a declared-files fixture record\n"
            "When the store reads its declared files\n"
            "Then the seam answers deterministically\n"
        ),
    }
    data.update(overrides)
    return data


def dump_ac_yaml(ac_id: str, **overrides: Any) -> str:
    """Serialize a fixture AC record with the REAL yaml.safe_dump (S2h.2)."""
    return yaml.safe_dump(
        default_ac_fields(ac_id, **overrides), allow_unicode=True, sort_keys=False
    )


def write_ac_yaml(store_root: Path, ac_id: str, subdir: str = "ac-driven-dev", **overrides: Any) -> Path:
    """Write one real, yaml.safe_dump-serialized AC file under store_root.

    Args:
        store_root: The docs/acceptance-criteria/ directory of a temp store
            (or temp repo root's docs/acceptance-criteria/).
        ac_id: The AC id (also the filename stem).
        subdir: Component subdirectory under store_root.
        **overrides: Fields overriding default_ac_fields()'s baseline.

    Returns:
        Path to the written .yaml file.
    """
    target_dir = store_root / subdir
    target_dir.mkdir(parents=True, exist_ok=True)
    path = target_dir / f"{ac_id}.yaml"
    path.write_text(dump_ac_yaml(ac_id, **overrides), encoding="utf-8")
    return path


def init_repo_root(root: Path) -> Path:
    """Create root/docs/acceptance-criteria/ and return it."""
    store_root = root / _AC_STORE_REL
    store_root.mkdir(parents=True, exist_ok=True)
    return store_root


def copy_real_schema_into(root: Path) -> None:
    """Copy the REAL config/ac_store_schema.json into root/config/, mirroring
    the established convention in unit_tests/commit_guardian/test_check_ac_schema.py
    (_write_ac_file), so the hook's jsonschema-available branch is exercised.
    """
    if SCHEMA_FILE.is_file():
        config_dir = root / "config"
        config_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(SCHEMA_FILE, config_dir / "ac_store_schema.json")


def init_git_index(root: Path) -> None:
    """git init + minimal identity config, so a REAL temporary index exists."""
    subprocess.run(["git", "init", "-q"], cwd=str(root), check=True, capture_output=True)
    subprocess.run(
        ["git", "config", "user.email", "test-writer@example.invalid"],
        cwd=str(root), check=True, capture_output=True,
    )
    subprocess.run(
        ["git", "config", "user.name", "test-writer"], cwd=str(root), check=True, capture_output=True,
    )


def git_add_all(root: Path) -> None:
    """Stage every file under root into the REAL temporary index."""
    subprocess.run(["git", "add", "-A"], cwd=str(root), check=True, capture_output=True)


def git_commit_all(root: Path, message: str = "fixture baseline") -> None:
    """Stage and commit everything under root, establishing a real HEAD.

    Used by tests that need to edit-and-restage a file that already exists
    at HEAD (e.g. "a change that edits only F's notes"), so the hook's own
    HEAD-vs-staged diff machinery is exercised against a real prior commit
    rather than a same-commit add.
    """
    git_add_all(root)
    subprocess.run(
        ["git", "commit", "-q", "-m", message], cwd=str(root), check=True, capture_output=True,
    )


def run_hook_against_real_index(root: Path, extra_env: dict[str, str] | None = None) -> CliRun:
    """Run the CANONICAL commit_guardian check_ac_schema.py hook as a real
    subprocess against a REAL temporary git index staged under `root` — no
    HOOK_TEST_STAGED_FILES shortcut. The hook's own `_get_staged_ac_paths()`
    runs `git diff --cached --name-only --diff-filter=AM` with the child
    process's cwd, so cwd=root is load-bearing here.

    Args:
        root: A git-initialised temporary repository root with files already
            staged via git_add_all().
        extra_env: Additional environment variables (e.g. HOOK_ROOT,
            PYTHONPATH for the jsonschema-unavailable shadow trick).

    Returns:
        A CliRun with the hook's exit code, stdout, and stderr.
    """
    env = os.environ.copy()
    env["HOOK_ROOT"] = str(root)
    if extra_env:
        env.update(extra_env)
    proc = subprocess.run(
        [sys.executable, str(CHECK_AC_SCHEMA_HOOK)],
        cwd=str(root),
        env=env,
        capture_output=True,
        text=True,
        timeout=60,
    )
    return CliRun(proc.returncode, proc.stdout, proc.stderr)


def run_validate_ac_schema(*paths: Path, extra_env: dict[str, str] | None = None) -> CliRun:
    """Run the REAL scripts/ac_store/validate_ac_schema.py CLI as a subprocess.

    Args:
        *paths: Absolute AC YAML file paths (or a directory) to validate.
        extra_env: Additional environment variables (e.g. the
            jsonschema-unavailable shadow PYTHONPATH).

    Returns:
        A CliRun with the validator's exit code, stdout, and stderr.
    """
    env = os.environ.copy()
    if extra_env:
        env.update(extra_env)
    proc = subprocess.run(
        [sys.executable, str(VALIDATE_AC_SCHEMA_CLI), *[str(p) for p in paths]],
        cwd=str(REPO_ROOT),
        env=env,
        capture_output=True,
        text=True,
        timeout=60,
    )
    return CliRun(proc.returncode, proc.stdout, proc.stderr)


def force_jsonschema_unavailable_env(tmp_path: Path) -> dict[str, str]:
    """Build an env override that makes `import jsonschema` raise ImportError
    inside a child subprocess, without touching the real installed package —
    exercising check_ac_schema.py's / validate_ac_schema.py's manual-fallback
    branch for real, exactly as it would run in an environment where the
    jsonschema dependency is genuinely absent.

    Mechanism: writes a shadow `jsonschema.py` (a real, importable Python
    module whose only statement raises ImportError) into an otherwise-empty
    directory and prepends that directory to PYTHONPATH, so the real
    site-packages `jsonschema` package is shadowed for this subprocess only.
    """
    shadow_dir = tmp_path / "_shadow_no_jsonschema"
    shadow_dir.mkdir(parents=True, exist_ok=True)
    (shadow_dir / "jsonschema.py").write_text(
        textwrap.dedent(
            """\
            raise ImportError("jsonschema forced unavailable for test")
            """
        ),
        encoding="utf-8",
    )
    existing = os.environ.get("PYTHONPATH", "")
    new_path = str(shadow_dir) + (os.pathsep + existing if existing else "")
    return {"PYTHONPATH": new_path}


def write_real_file(root: Path, rel_path: str, content: str = "# fixture\n") -> Path:
    """Write a real file at root/rel_path (POSIX-style rel_path), creating
    parent directories, for existence-vs-marker checks against a temp tree.
    """
    path = root / rel_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path
