"""
MODULE: generate_doc_index
GOAL: Walk the docs tree and generate a pull-based documentation index (docs/INDEX.md)
    so BA and IT PO agents can discover what documentation exists and where it lives
    without injecting all docs upfront.
BUSINESS CONTEXT: Context injection at spawn time fills the window with irrelevant
    docs. This script produces a lightweight index (~50-100 lines) that maps every
    doc topic to its file path and a one-line description.  Agents read the index
    first, then pull only the docs they need for the current ticket.
ARCHITECTURE: Single-module script. Walk each canonical docs subdirectory in a
    fixed order. For each file, extract a one-line description from the YAML
    frontmatter ``description:`` field (if present) or fall back to the first
    non-blank, non-heading line. Emit one Markdown table per category. Write the
    result to ``docs/INDEX.md``.  The script is designed to be called from
    ``build.py`` (integration) and directly from the command line
    (``python scripts/generate_doc_index.py``).
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_HEADER_TEMPLATE = """\
# Documentation Index

> **Auto-generated — do not edit manually.**
> Run `python scripts/generate_doc_index.py` to regenerate.
>
> Generated: {timestamp}

This index lists every documentation file in the project.  BA and IT PO agents
should read this index first, identify which docs are relevant to the current
task, then pull only those files.

"""

_FOOTER = """\
---
*Index generated by `scripts/generate_doc_index.py`.*
"""

# Category definitions: (heading, relative docs sub-path, recursive)
# Order is intentional: most-used categories appear first.
_CATEGORIES = [
    ("Components", "docs/architecture/components", True),
    ("Architecture Diagrams", "docs/architecture", False),
    ("Architecture Decision Records (ADRs)", "docs/architecture/adrs", False),
    ("How-To Guides", "docs/how-to", True),
    ("Reference", "docs/reference", True),
    ("Explanation", "docs/explanation", True),
    ("Conventions", "docs/conventions", True),
    ("Retrospectives", "docs/retrospectives", True),
    ("Glossary", "docs/glossary.md", None),  # None means single file
]

# Files that are explicitly excluded from every category scan.
_ALWAYS_EXCLUDE = {"README.md", "INDEX.md"}


# ---------------------------------------------------------------------------
# Description extraction
# ---------------------------------------------------------------------------

def _extract_description(path: Path) -> str:
    """Return a one-line description for the given Markdown file.

    Tries sources in order:
    1. YAML frontmatter ``description:`` field.
    2. YAML frontmatter ``title:`` field (fallback within frontmatter).
    3. First non-blank, non-heading, non-comment line of the document body.
    4. Fallback string "(no description)".

    Args:
        path: Absolute or repo-relative path to a Markdown file.

    Returns:
        A single-line string suitable for use in an index table cell.
        Leading/trailing whitespace is stripped.  If the source text
        contains a pipe (``|``) it is replaced with a space to avoid
        breaking the Markdown table.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        log.warning("Cannot read %s: %s", path, exc)
        return "(unreadable)"

    title_fallback: str | None = None

    # --- Attempt frontmatter description or title ---
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            frontmatter = text[3:end]
            for line in frontmatter.splitlines():
                # Prefer description: over title:
                m_desc = re.match(r"^description\s*:\s*['\"]?(.*?)['\"]?\s*$", line)
                if m_desc:
                    desc = m_desc.group(1).strip().strip("'\"")
                    if desc:
                        return desc.replace("|", " ")
                # Record title: as a fallback candidate
                if title_fallback is None:
                    m_title = re.match(r"^title\s*:\s*['\"]?(.*?)['\"]?\s*$", line)
                    if m_title:
                        candidate = m_title.group(1).strip().strip("'\"")
                        if candidate:
                            title_fallback = candidate.replace("|", " ")

    if title_fallback is not None:
        return title_fallback

    # --- Fall back to first non-blank, non-heading, non-comment body line ---
    in_frontmatter = text.startswith("---")
    past_frontmatter = not in_frontmatter
    in_html_comment = False
    for line in text.splitlines():
        if in_frontmatter:
            if line.strip() == "---":
                in_frontmatter = False
                past_frontmatter = True
            continue
        # Track multi-line HTML comment blocks.
        if in_html_comment:
            if "-->" in line:
                in_html_comment = False
            continue
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("<!--"):
            if "-->" not in stripped:
                in_html_comment = True
            continue  # skip HTML comment openers (single- or multi-line)
        if stripped.startswith("#"):
            continue  # skip headings
        if stripped.startswith(">"):
            continue  # skip blockquotes (often boilerplate)
        return stripped[:120].replace("|", " ")

    return "(no description)"


# ---------------------------------------------------------------------------
# Category rendering
# ---------------------------------------------------------------------------

def _render_single_file(heading: str, path: Path, repo_root: Path) -> str:
    """Render a single-file category (e.g. docs/glossary.md).

    Args:
        heading: Section heading string.
        path: Absolute path to the single file.
        repo_root: Absolute path to the repo root (used for relative links).

    Returns:
        Markdown section string.
    """
    if not path.exists():
        return f"## {heading}\n\nNo docs found.\n\n"

    rel = path.relative_to(repo_root)
    desc = _extract_description(path)
    return f"## {heading}\n\n- [{rel}]({rel}) — {desc}\n\n"


def _render_directory(
    heading: str,
    dir_path: Path,
    repo_root: Path,
    recursive: bool,
) -> str:
    """Render a multi-file directory category as a Markdown table.

    Args:
        heading: Section heading string.
        dir_path: Absolute path to the docs subdirectory to scan.
        repo_root: Absolute path to the repo root.
        recursive: When True, scan subdirectories recursively.

    Returns:
        Markdown section string.  Empty directories emit "No docs found."
    """
    if not dir_path.exists():
        return f"## {heading}\n\nNo docs found.\n\n"

    glob_pattern = "**/*.md" if recursive else "*.md"
    files = sorted(dir_path.glob(glob_pattern))
    files = [
        f for f in files
        if f.name not in _ALWAYS_EXCLUDE and f.is_file()
    ]

    if not files:
        return f"## {heading}\n\nNo docs found.\n\n"

    rows: list[str] = []
    for f in files:
        rel = f.relative_to(repo_root)
        name = f.stem.replace("-", " ").replace("_", " ")
        desc = _extract_description(f)
        rows.append(f"| {name} | [{rel}]({rel}) | {desc} |")

    table = "\n".join(
        [
            "| Name | Path | Description |",
            "|------|------|-------------|",
        ]
        + rows
    )
    return f"## {heading}\n\n{table}\n\n"


# ---------------------------------------------------------------------------
# Index generation
# ---------------------------------------------------------------------------

def generate_index(repo_root: Path) -> str:
    """Generate the full INDEX.md content for the given repo root.

    Walks each canonical category defined in ``_CATEGORIES``, builds one
    Markdown section per category, and prepends the standard auto-generated
    header.

    Args:
        repo_root: Absolute path to the repository root.  All relative paths
            in the generated index are computed relative to this directory.

    Returns:
        Complete INDEX.md content as a UTF-8 string.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    sections: list[str] = [_HEADER_TEMPLATE.format(timestamp=timestamp)]

    for heading, rel_path, recursive in _CATEGORIES:
        abs_path = repo_root / rel_path
        if recursive is None:
            # Single-file entry
            sections.append(_render_single_file(heading, abs_path, repo_root))
        else:
            sections.append(_render_directory(heading, abs_path, repo_root, recursive))

    sections.append(_FOOTER)
    return "".join(sections)


def write_index(repo_root: Path, output_path: Path | None = None) -> Path:
    """Generate the doc index and write it to disk.

    Args:
        repo_root: Absolute path to the repository root.
        output_path: Destination file.  Defaults to ``<repo_root>/docs/INDEX.md``.

    Returns:
        The absolute path to the written file.

    Raises:
        OSError: If the target file cannot be written.
    """
    if output_path is None:
        output_path = repo_root / "docs" / "INDEX.md"

    content = generate_index(repo_root)

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")
    except OSError:
        log.exception("Failed to write index to %s", output_path)
        raise
    else:
        return output_path


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    """CLI wrapper for index generation.

    Args:
        argv: Argument list (defaults to sys.argv[1:]).

    Returns:
        0 on success, non-zero on failure.
    """
    parser = argparse.ArgumentParser(
        description="Generate docs/INDEX.md by walking the docs tree."
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help=(
            "Repo root directory.  Defaults to the parent of the scripts/ "
            "directory containing this file."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output path.  Defaults to <repo-root>/docs/INDEX.md.",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose logging.",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.WARNING,
        format="%(levelname)s: %(message)s",
    )

    # Resolve repo root: default to parent of the directory containing this script.
    repo_root: Path
    if args.repo_root is not None:
        repo_root = args.repo_root.resolve()
    else:
        repo_root = Path(__file__).resolve().parent.parent

    output_path: Path | None = args.output.resolve() if args.output else None

    try:
        written = write_index(repo_root, output_path)
    except OSError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    else:
        print(f"Index written to {written}")
        return 0


if __name__ == "__main__":
    sys.exit(main())
